spring:
  application:
    name: plazoleta-restaurant-ms
  #Configuracion PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/powerup_pragma
    username: johandiaz
    password:
    driver-class-name: org.postgresql.Driver

  # MongoDB para trazabilidad HU-17
  data:
    mongodb:
      uri: mongodb://localhost:27017/plazoleta_trazabilidad
      auto-index-creation: true

  #Comfiguracion JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

#Configuracion JWT
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 #24 horas en milisegundos

#Configuracion OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    com.pragma.powerup: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG

appDescription: "Pragma Powerup - Plaza de Comidas"
appVersion: "1.0.0"