spring:
  application:
    name: plazoleta-restaurant-ms

  # Configuracion PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/powerup_pragma
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Comfiguracion JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true


server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

# Configuracion OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    root: INFO
    com.pragma.powerup: DEBUG
    org.hibernate.SQL: DEBUG  # Linea de SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # linea de Parámetros SQL
appDescription: "Pragma Powerup - Plaza de Comidas"
appVersion: "1.0.0"
